build:
  name: Test via API for bll-contracting
  repository: 6c68508f-62a2-4d9f-9707-9f2d2a418147
release:
  name: Test via API for bll-contracting
  esb: true
  rabbitmq: true
  variables:
    BLL_DO_AUDITING: do_uda
