{{ $project := "Webfoundation" }}
{{ $common_values_file := "./values/values.yaml" }}

{{ $bll_values_file := "./values/bll/values.yaml" }}
{{ $bll_common_chart := "./charts/bll-common" }}
{{ $bll_group := "api" }}

templates:
  bll: &bll
    missingFileHandler: Warn
    chart: {{ $bll_common_chart }}
    namespace: {{ $project }}
    labels:
      group: {{ $bll_group }}
      component: "{{`{{ .Release.Name }}`}}"
    values:
      - "./values/values.yaml"
      - "./values/bll/values.yaml"
      - "./values/bll/{{`{{ .Release.Name }}`}}/values.yaml"

releases:
  - name: "bll-contracting"
    <<: *bll
  - name: "bll-contact"
    <<: *bll
