{{ $bll_pipelines_chart := "./bll-pipelines" }}
{{ $common_values_file := "./values/values.yaml" }}
{{ $bll_group := "api" }}

releases:
  - name: "bll-contracting"
    namespace: Webfoundation
    labels:
      group: {{ $bll_group }}
      component: "bll-contracting"
    chart: {{ $bll_pipelines_chart }}
    values:
      - {{ $common_values_file }}
      - name: Test via API for bll-contracting
      - build:
          name: BLL-Contracting CI
          path: \API\
      - esb: true
      - rabbitmq: true
      - database: false
      - variables:
          BLL_DO_AUDITING: do_uda
  - name: "bll-contact"
    namespace: Webfoundation
    labels:
      group: {{ $bll_group }}
      component: bll-contact
    chart: {{ $bll_pipelines_chart }}
    values:
      - {{ $common_values_file }}
      - name: Test via API for bll-contact
      - build:
          name: BLL-Contact CI
          path: \API\
      - esb: false
      - rabbitmq: false
      - database: false     