{{ $project := "Webfoundation" }}
{{ $common_values_file := "./values/values.common.yaml" }}
{{ $bll_values_file := "./values/values.bll.yaml" }}
{{ $bll_pipelines_chart := "./bll-pipelines" }}
{{ $bll_group := "api" }}

releases:
  - name: "bll-contracting"
    namespace: {{ $project }}
    labels:
      group: {{ $bll_group }}
      component: "bll-contracting"
    chart: {{ $bll_pipelines_chart }}
    values:
      - {{ $common_values_file }}
      - {{ $bll_values_file }}
      - build:
          name: Test via API for bll-contracting
          repository: 6c68508f-62a2-4d9f-9707-9f2d2a418147
        release:
          name: Test via API for bll-contracting
          esb: true
          rabbitmq: true
          variables:
            BLL_DO_AUDITING: do_uda
  - name: "bll-contact"
    namespace: {{ $project }}
    labels:
      group: {{ $bll_group }}
      component: bll-contact
    chart: {{ $bll_pipelines_chart }}
    values:
      - {{ $common_values_file }}
      - {{ $bll_values_file }}
      - build:
          name: Test via API for bll-contact
          repository: 60f95ef8-bd9a-4ade-87b2-751753700cb3
        release:
          name: Test via API for bll-contact
