{{ $project := "Webfoundation" }}
{{ $common_values_file := "./values/values.yaml" }}

{{ $bll_values_file := "./values/bll/values.yaml" }}
{{ $bll_common_chart := "./charts/bll-common" }}
{{ $bll_group := "api" }}

templates:
  bll: &bll
    missingFileHandler: Warn
    chart: {{ $bll_common_chart }}
    namespace: {{ $project }}
    values:
      - "./values/values.yaml"
      - "./values/bll/values.yaml"
      - "./values/bll/{{`{{ .Release.Labels.component }}`}}/values.yaml"

releases:
  - name: "bll-contracting"
    labels:
      group: {{ $bll_group }}
      component: "bll-contracting"
    <<: *bll
  - name: "bll-contact"
    labels:
      group: {{ $bll_group }}
      component: bll-contact
    <<: *bll
