group: bll

build:
  path: \Other\POC
  triggers:
    continuousIntegration:
      branchFilters:
        - +refs/heads/rc*
        - +refs/heads/feature/*
        - +refs/heads/renovate/*
  variableGroups:
    - Docker Builds
  jdkVersion: '1.11'

  releaseClientBuildPipeline:
    enabled: false
    path: \Other\POC

  nightlyBuildPipeline:
    enabled: true
    path: \Other\POC\Nightly builds
    triggers:
      schedule:
        branchFilters:
          - +refs/heads/master
          - +refs/heads/rc
        timeZoneId: Romance Standard Time
        startHours: 0
        startMinutes: 0

release:
  path: \Other\POC

  esb: false
  rabbitmq: false
  database: false

  variables:
    BLL_LOG_LEVEL: INFO
    K8S_AGENT_POOL: general
    K8S_NAMESPACE: core
    REPLICAS: '2'
    ROOT_LOG_LEVEL: INFO

  secretValues:
    BLL_JWKS_ENCRYPTION: $(bll-jwks-encryption)
    BLL_JWKS_SIGNATURE: $(bll-jwks-signature)

  stages:
    1_INT_NE:
      esb: ihn519
    2_INT_NE:
      esb: ihn519
    3_ACC_WE:
      esb: hhn544
    4_ACC_NE:
      esb: hhn544
    5_PRD_WE:
      esb: gim597
    6_PRD_NE:
      esb: gim597
