group: bll

build:
  path: \Other\POC
  buildNameFormat: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:_r)
  triggers:
    continuousIntegration:
      branchFilters:
        - +refs/heads/rc*
        - +refs/heads/feature/*
        - +refs/heads/renovate/*
  agentPool: Default-Linux
  variableGroups:
    - Docker Builds
  jdkVersion: '1.11'

  releaseClientBuildPipeline:
    enabled: false
    path: \Other\POC

  nightlyBuildPipeline:
    enabled: true
    path: \Other\POC\Nightly builds
    triggers:
      schedule:
        branchFilters:
          - +refs/heads/master
          - +refs/heads/rc
        timeZoneId: Romance Standard Time
        startHours: 0
        startMinutes: 0

release:
  path: \Other\POC
  releaseNameFormat: Release-$(rev:r)
  description: Created via script

  esb: false
  rabbitmq: false
  database: false

  variables:
    BLL_LOG_LEVEL: INFO
    K8S_AGENT_POOL: general
    K8S_NAMESPACE: core
    REPLICAS: '2'
    ROOT_LOG_LEVEL: INFO

  secretValues:
    BLL_JWKS_ENCRYPTION: $(bll-jwks-encryption)
    BLL_JWKS_SIGNATURE: $(bll-jwks-signature)

  stages:
    1_INT_NE:
      name: INT-WE
      variables:
        BLL_LOG_LEVEL: DEBUG
      variableGroups:
        - Config INT
        - Config INT-WE
      agentPool: MS-NONPRD-WE
      vault: webfoundation-int-akv
      azureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
      esb: ihn519
      preApprovers: []
      postApprovers: []
    2_INT_NE:
      name: INT-NE
      variables:
        BLL_LOG_LEVEL: DEBUG
      variableGroups:
        - Config INT
        - Config INT-NE
      agentPool: MS-NONPRD-NE
      vault: webfoundation-int-akv
      azureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
      esb: ihn519
      preApprovers: []
      postApprovers: []
    3_ACC_WE:
      name: ACC-WE
      variables:
        BLL_LOG_LEVEL: DEBUG
      variableGroups: # [Config ACC, Config ACC-WE] I don't have access
        - Config INT
        - Config INT-WE
      agentPool: MS-NONPRD-WE
      vault: webfoundation-acc-akv
      azureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
      esb: hhn544
      preApprovers:
        - "c48d7901-feca-403b-b698-cf99c6e7d602"
      postApprovers: []
    4_ACC_NE:
      name: ACC-NE
      variableGroups: # [Config ACC, Config ACC-NE] I don't have access
        - Config INT
        - Config INT-NE
      agentPool: MS-NONPRD-NE
      vault: webfoundation-acc-akv
      azureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
      esb: hhn544
      preApprovers:
        - "c48d7901-feca-403b-b698-cf99c6e7d602"
      postApprovers: []
    5_PRD_WE:
      name: PRD-WE
      variableGroups: # [Config PRD, Config PRD-WE] I don't have access
        - Config INT
        - Config INT-WE
      agentPool: MS-NONPRD-WE # MS-PRD-WE I don't have access
      vault: webfoundation-prd-akv
      azureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a # f9da387b-09b3-4d7a-aea4-6a95dd060a16 I don't have access
      esb: gim597
      preApprovers:
        - "e9a38fdf-a890-4227-909e-c438dc074464"
      postApprovers: []
    6_PRD_NE:
      name: PRD-NE
      variableGroups: # [Config PRD, Config PRD-NE] I don't have access
        - Config INT
        - Config INT-NE
      agentPool: MS-NONPRD-NE # MS-PRD-NE I don't have access
      vault: webfoundation-prd-akv
      azureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a # f9da387b-09b3-4d7a-aea4-6a95dd060a16 I don't have access
      esb: gim597
      preApprovers:
        - "e9a38fdf-a890-4227-909e-c438dc074464"
      postApprovers: []
