---
apiVersion: azure-devops
kind: BuildDefinition
metadata:
  labels:
    test: label
spec:
  name: My Build Pipeline
  path: \
  process:
    phases:
      - steps:
          - displayName: Bash Script
            task:
              name: Bash
              versionSpec: 3.*
            inputs:
              targetType: inline
              script: |
                echo 'Hello world' > ${BUILD_ARTIFACTSTAGINGDIRECTORY}/hello.txt
          - displayName: Publish Artifact
            task:
              name: Publish build artifacts
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: drop
          - displayName: Execute my build task group
            task:
              name: My Build Task Group
              definitionType: metaTask
            inputs:
              my.build.parameter: My Build Parameter
    target:
      agentSpecification:
        identifier: ubuntu-18.04
  repository:
    name: My Git Repository
  queue:
    name: Azure Pipelines
  variables:
    myBuildVar: build
    myOverridableBuildVar:
      value: overridable
      allowOverride: true
  variableGroups:
    - My Variable Group
