apiVersion: azure-devops
kind: ReleaseDefinition
metadata:
  labels:
    test: label
spec:
  name: My Release Pipeline
  path: \
  environments:
    - name: Stage 1
      variables:
        myStageVar: stage
      variableGroups:
        - My Variable Group
      deployPhases:
        - deploymentInput:
            agentSpecification:
              identifier: vs2017-win2016
            queueId: Azure Pipelines
          name: Agent job
          workflowTasks:
            - taskName: Bash
              version: 3.*
              inputs:
                targetType: inline
                name: Bash Script
                script: |
                  echo 'Hello world'
  artifacts:
    - type: Build
      alias: build-artifact
      definitionReference:
        definition:
          name: My Build Pipeline
          path: \
  variables:
    myReleaseVar: release
