---
apiVersion: azure-devops
kind: TaskGroup
spec:
  tasks:
    - displayName: Bash Script
      inputs:
        targetType: inline
        script: |
          echo 'Hello'
      task:
        name: Bash
        versionSpec: 3.*
    - displayName: Bash Script
      inputs:
        targetType: inline
        script: |
          echo 'from task group with input $(my.task.group.parameter)'
      task:
        name: Bash
        versionSpec: 3.*
  name: My Task Group
  inputs:
    - name: my.task.group.parameter
      label: My Task Group Parameter
