---
apiVersion: azure-devops
kind: BuildDefinition
metadata:
  labels:
    group: bll
    component: {{ .Release.Name }}
spec:
  name: Test via API for bll-contracting
  path: \Other\Poc
  project:
    id: 5a4ec25a-2f9d-4947-9937-d4347eaceadd
  buildNumberFormat: '$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:_r)'
  triggers:
    - branchFilters:
        - +refs/heads/rc*
        - +refs/heads/feature/*
        - +refs/heads/renovate/*
      triggerType: 2
  variableGroups:
    - id: 33
  process:
    phases:
      - steps:
          - displayName: Maven pom.xml
            task:
              id: ac4ee482-65da-4485-a532-7b085873e532 # TODO by name
              versionSpec: 3.*
              definitionType: task
            inputs:
              goals: clean deploy -U
              publishJUnitResults: 'false'
              jdkVersion: '1.11'
              mavenFeedAuthenticate: 'true'
          - displayName: 'Publish Artifact: k8s'
            task:
              id: 2ff763a7-ce83-4e1f-bc89-0ae63477cebe
              versionSpec: 1.*
              definitionType: task
            inputs:
              PathtoPublish: k8s
              ArtifactName: k8s
          - displayName: 'Task group: Publish api-definitions artifact '
            task:
              id: 2793ff62-78af-4351-bdbc-03da6a37eda4
              versionSpec: 1.*
              definitionType: metaTask
            inputs: {}
          - displayName: 'Task group: Build and push Docker image to ALM Nexus'
            task:
              id: 001f6df6-2576-4520-ae2f-897b788a6017
              versionSpec: 1.*
              definitionType: metaTask
            inputs:
              build.arguments: ''
              docker.baseimage: $(OPENJDK11_BASE_IMAGE)
              dockerfile: ''
              image.name: bll-contracting
  repository:
    id: 6c68508f-62a2-4d9f-9707-9f2d2a418147 # by name
  queue:
    id: 43
