---
apiVersion: azure-devops/v0.1
kind: ReleaseDefinition
metadata:
  name: {{ default .Release.Name .Values.name }}
  path: "{{ .Values.path }}"
  project: {{ .Values.project.name }}
  labels:
    group: bll
spec:
  description: {{ .Values.description }}
  releaseNameFormat: {{ .Values.releaseNameFormat }}
  {{ if .Values.variables -}}
  variables:
    {{ range $name, $value := .Values.variables -}}
    {{ $name }}:
      value: {{ $value }}
    {{ end }} 
    {{ if .Values.rabbitmq -}}
    RABBITMQ_USERNAME:
      value: {{ .Release.Name }}
    {{ end }}  
  {{ end -}}
  environments:
  {{ range $index, $stage := .Values.stages -}}
  - name: {{ $stage.name }}
    rank: {{ add $index 1 }}
    environmentOptions:
      emailNotificationType: Always
      publishDeploymentStatus: true
    executionPolicy:
      concurrencyCount: 1
    retentionPolicy:
      daysToKeep: 30
      releasesToKeep: 10
      retainBuild: true
    {{ if $stage.variables -}}
    variables:
      {{ range $name, $value := $stage.variables -}}
      {{ $name }}:
        value: {{ $value }}
      {{- end }}
    {{ end -}}        
    {{ if $stage.variableGroups -}}
    variableGroups:
    {{ range $variableGroup := $stage.variableGroups -}}
    - {{ $variableGroup }}
    {{ end -}}
    {{ end -}}     
    deployPhases:
    - name: Agent phase
      rank: 1
      phaseType: 1
      deploymentInput:
        queueId: {{ $stage.agentPool }}
      workflowTasks:
      - taskId: 1e244d32-2dd4-4165-96fb-b7441ca9331e
        version: 1.*
        name: 'Azure Key Vault: {{ $stage.vault }}'
        enabled: true
        definitionType: task
        inputs:
          ConnectedServiceName: {{ $stage.azureSubscription }}
          KeyVaultName: {{ $stage.vault }}
          SecretsFilter: "*"
      {{ if $.Values.rabbitmq -}}
      - taskId: 93a67d85-4982-4e19-87dd-29311c974748
        version: 2.*
        name: 'Task group: Create RabbitMQ user'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: {{ $stage.azureSubscription }}
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          RabbitMQPassword: "$(rabbitmq-{{ $.Release.Name }}-password)"
          RabbitMQPod: ''
          RabbitMQUsername: "$(RABBITMQ_USERNAME)"
          RabbitMQVirtualHost: ''
      {{- end }}
      - taskId: 76a92167-7c70-4b54-ba35-13d5819c9b1e
        version: 2.*
        name: 'Task group: K8S Deploy V3 {{ $.Release.Name }}'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: {{ $stage.azureSubscription }}
          HelmArtifact: ''
          KubernetesDeploymentName: {{ $.Release.Name }}
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          KubernetesObjectType: ''
          SecretValues: {{ if $.Values.rabbitmq }}RABBITMQ_PASSWORD=$(rabbitmq-{{ $.Release.Name }}-password),{{ end -}}
                        {{ if $.Values.esb }}ESB_KEYSTORE_PW=$(esb-{{ $stage.esb }}-password),{{ end -}}
                        {{ if $.Values.esb }}ESB_KEYSTORE_FILE=$(esb-{{ $stage.esb }}-value),{{ end -}}
                        {{ $first := true -}}
                        {{ range $name, $value := $.Values.secretValues -}}
                          {{ if $first -}}
                            {{ $first = false -}}
                          {{else -}}
                            ,
                          {{- end }}
                          {{- $name }}={{ $value }}
                        {{- end }}                      
    preDeployApprovals:
    {{- if gt ($stage.preApprovers | len) 0 }}
      approvals:
      {{ range $index, $approver := $stage.preApprovers -}}      
      - rank: {{ add $index 1 }}
        isAutomated: false
        isNotificationOn: false
        approver:
          id: {{ $approver }}
          isContainer: true
      approvalOptions:
        releaseCreatorCanBeApprover: true 
      {{- end }}   
    {{- else }}
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
    {{- end }}
    postDeployApprovals:
    {{- if gt ($stage.postApprovers | len ) 0 }}
      approvals:
      {{ range $index, $approver := $stage.postApprovers -}}      
      - rank: {{ add $index 1 }}
        isAutomated: false
        isNotificationOn: false
        approver:
          id: {{ $approver }}
          isContainer: true
      approvalOptions:
        releaseCreatorCanBeApprover: true 
      {{- end }}   
    {{- else }}
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
    {{- end }}
  {{ end -}}
  artifacts:
  - type: Build
    alias: {{ .Values.artifactAlias }}
    definitionReference:
      defaultVersionType:
        id: latestType
        name: Latest
      definition:
        id: '{{ .Values.buildId }}'
      project:
        id: {{ .Values.project.id }}