---
apiVersion: azure-devops/v0.1
kind: ReleaseDefinition
metadata:
  labels:
    group: {{ .Values.group }}
    component: {{ .Release.Name }}
spec:
  name: {{ default .Release.Name .Values.release.name }}
  path: {{ .Values.release.path }}
  description: {{ .Values.release.description }}
  releaseNameFormat: {{ .Values.release.releaseNameFormat }}
  {{ if .Values.release.variables -}}
  variables:
    {{ range $name, $value := .Values.release.variables -}}
    {{ $name }}:
      value: {{ $value }}
    {{ end }}
    {{ if .Values.release.rabbitmq -}}
    RABBITMQ_USERNAME:
      value: {{ .Release.Name }}
    {{ end }}
  {{ end -}}
  environments:
  {{ range $stage := .Values.release.stages -}}
  - name: {{ $stage.name }}
    retentionPolicy:
      releasesToKeep: 10
    {{ if $stage.variables -}}
    variables:
      {{ range $name, $value := $stage.variables -}}
      {{ $name }}:
        value: {{ $value }}
      {{- end }}
    {{ end -}}
    {{ if $stage.variableGroups -}}
    variableGroups:
    {{ range $variableGroup := $stage.variableGroups -}}
    - {{ $variableGroup }}
    {{ end -}}
    {{ end -}}
    deployPhases:
    - name: Agent phase
      deploymentInput:
        queueId: {{ $stage.agentPool }}
      workflowTasks:
      - taskId: 1e244d32-2dd4-4165-96fb-b7441ca9331e
        version: 1.*
        name: 'Azure Key Vault: {{ $stage.vault }}'
        definitionType: task
        inputs:
          ConnectedServiceName: {{ $stage.azureSubscription }}
          KeyVaultName: {{ $stage.vault }}
          SecretsFilter: "*"
      {{ if $.Values.release.rabbitmq -}}
      - taskId: 93a67d85-4982-4e19-87dd-29311c974748
        version: 2.*
        name: 'Task group: Create RabbitMQ user'
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: {{ $stage.azureSubscription }}
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          RabbitMQPassword: "$(rabbitmq-{{ $.Release.Name }}-password)"
          RabbitMQPod: ''
          RabbitMQUsername: "$(RABBITMQ_USERNAME)"
          RabbitMQVirtualHost: ''
      {{- end }}
      - taskId: 76a92167-7c70-4b54-ba35-13d5819c9b1e
        version: 2.*
        name: 'Task group: K8S Deploy V3 {{ $.Release.Name }}'
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: {{ $stage.azureSubscription }}
          HelmArtifact: ''
          KubernetesDeploymentName: {{ $.Release.Name }}
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          KubernetesObjectType: ''
          SecretValues: {{ if $.Values.release.rabbitmq }}RABBITMQ_PASSWORD=$(rabbitmq-{{ $.Release.Name }}-password),{{ end -}}
                        {{ if $.Values.release.esb }}ESB_KEYSTORE_PW=$(esb-{{ $stage.esb }}-password),{{ end -}}
                        {{ if $.Values.release.esb }}ESB_KEYSTORE_FILE=$(esb-{{ $stage.esb }}-value),{{ end -}}
                        {{ $first := true -}}
                        {{ range $name, $value := $.Values.release.secretValues -}}
                          {{ if $first -}}
                            {{ $first = false -}}
                          {{else -}}
                            ,
                          {{- end }}
                          {{- $name }}={{ $value }}
                        {{- end }}
    {{ if gt ($stage.preApprovers | len) 0 -}}
    preDeployApprovals:
      approvals:
      {{ range $approver := $stage.preApprovers -}}
      - approver:
          id: {{ $approver }}
          isContainer: true
      approvalOptions:
        releaseCreatorCanBeApprover: true
      {{- end }}
    {{- end }}
    {{ if gt ($stage.postApprovers | len ) 0 -}}
    postDeployApprovals:
      approvals:
      {{ range $approver := $stage.postApprovers -}}
      - approver:
          id: {{ $approver }}
          isContainer: true
      approvalOptions:
        releaseCreatorCanBeApprover: true
      {{- end }}
    {{- end }}
  {{ end -}}
  artifacts:
  - type: Build
    alias: {{ .Values.build.name }}
    definitionReference:
      defaultVersionType:
        id: latestType
        name: Latest
      definition:
        name: {{ .Values.build.name }}
        path:  {{ .Values.build.path }}
      project:
        id: {{ .Values.project.id }}
