---
apiVersion: azure-devops/v0.1
kind: ReleaseDefiniton
metadata:
  name: POC-Created-Via-API
spec:
  description: Testing via yaml
  path: "\\Other\\POC"
  releaseNameFormat: Release-$(rev:r)
  variables:
    BLL_DO_AUDITING:
      value: do_uda
    BLL_LOG_LEVEL:
      value: INFO
    K8S_AGENT_POOL:
      value: general
    K8S_NAMESPACE:
      value: core
    RABBITMQ_USERNAME:
      value: bll-contracting
    REPLICAS:
      value: '2'
    ROOT_LOG_LEVEL:
      value: INFO
  environments:
  - name: INT-WE
    rank: 1
    environmentOptions:
      emailNotificationType: Always
      publishDeploymentStatus: true
    executionPolicy:
      concurrencyCount: 1
    retentionPolicy:
      daysToKeep: 30
      releasesToKeep: 10
      retainBuild: true
    variables:
      BLL_LOG_LEVEL:
        value: DEBUG
    variableGroups:
    - 113
    - 25
    deployPhases:
    - name: Agent phase
      rank: 1
      phaseType: 1
      deploymentInput:
        queueId: 165
      workflowTasks:
      - taskId: 1e244d32-2dd4-4165-96fb-b7441ca9331e
        version: 1.*
        name: 'Azure Key Vault: webfoundation-int-akv'
        enabled: true
        definitionType: task
        inputs:
          ConnectedServiceName: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KeyVaultName: webfoundation-int-akv
          SecretsFilter: "*"
      - taskId: 93a67d85-4982-4e19-87dd-29311c974748
        version: 2.*
        name: 'Task group: Create RabbitMQ user'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          RabbitMQPassword: "$(rabbitmq-bll-contracting-password)"
          RabbitMQPod: ''
          RabbitMQUsername: "$(RABBITMQ_USERNAME)"
          RabbitMQVirtualHost: ''
      - taskId: 76a92167-7c70-4b54-ba35-13d5819c9b1e
        version: 2.*
        name: 'Task group: K8S Deploy V3 bll-contracting'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          HelmArtifact: ''
          KubernetesDeploymentName: bll-contracting
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          KubernetesObjectType: ''
          SecretValues: ESB_KEYSTORE_PW=$(esb-ihn519-password),ESB_KEYSTORE_FILE=$(esb-ihn519-value),BLL_JWKS_ENCRYPTION=$(bll-jwks-encryption),BLL_JWKS_SIGNATURE=$(bll-jwks-signature),RABBITMQ_PASSWORD=$(rabbitmq-bll-contracting-password)
    preDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
    postDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
  - name: INT-NE
    rank: 2
    environmentOptions:
      emailNotificationType: Always
      publishDeploymentStatus: true
    executionPolicy:
      concurrencyCount: 1
    retentionPolicy:
      daysToKeep: 30
      releasesToKeep: 10
      retainBuild: true
    variables:
      BLL_LOG_LEVEL:
        value: DEBUG
    variableGroups:
    - 113
    - 23
    deployPhases:
    - name: Agent phase
      rank: 1
      phaseType: 1
      deploymentInput:
        queueId: 164
      workflowTasks:
      - taskId: 1e244d32-2dd4-4165-96fb-b7441ca9331e
        version: 1.*
        name: 'Azure Key Vault: webfoundation-int-akv'
        enabled: true
        definitionType: task
        inputs:
          ConnectedServiceName: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KeyVaultName: webfoundation-int-akv
          SecretsFilter: "*"
      - taskId: 93a67d85-4982-4e19-87dd-29311c974748
        version: 2.*
        name: 'Task group: Create RabbitMQ user'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          RabbitMQPassword: "$(rabbitmq-bll-contracting-password)"
          RabbitMQPod: ''
          RabbitMQUsername: "$(RABBITMQ_USERNAME)"
          RabbitMQVirtualHost: ''
      - taskId: 76a92167-7c70-4b54-ba35-13d5819c9b1e
        version: 2.*
        name: 'Task group: K8S Deploy V3 bll-contracting'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          HelmArtifact: ''
          KubernetesDeploymentName: bll-contracting
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          KubernetesObjectType: ''
          SecretValues: ESB_KEYSTORE_PW=$(esb-ihn519-password),ESB_KEYSTORE_FILE=$(esb-ihn519-value),BLL_JWKS_ENCRYPTION=$(bll-jwks-encryption),BLL_JWKS_SIGNATURE=$(bll-jwks-signature),RABBITMQ_PASSWORD=$(rabbitmq-bll-contracting-password)
    preDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
    postDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
  - name: ACC-WE
    rank: 3
    environmentOptions:
      emailNotificationType: Always
      publishDeploymentStatus: true
    executionPolicy:
      concurrencyCount: 1
    retentionPolicy:
      daysToKeep: 30
      releasesToKeep: 10
      retainBuild: true
    variables:
      BLL_LOG_LEVEL:
        value: DEBUG
    variableGroups:
    - 113
    - 25
    deployPhases:
    - name: Agent phase
      rank: 1
      phaseType: 1
      deploymentInput:
        queueId: 165
      workflowTasks:
      - taskId: 1e244d32-2dd4-4165-96fb-b7441ca9331e
        version: 1.*
        name: 'Azure Key Vault: webfoundation-acc-akv'
        enabled: true
        definitionType: task
        inputs:
          ConnectedServiceName: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KeyVaultName: webfoundation-acc-akv
          SecretsFilter: "*"
      - taskId: 93a67d85-4982-4e19-87dd-29311c974748
        version: 2.*
        name: 'Task group: Create RabbitMQ user'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          RabbitMQPassword: "$(rabbitmq-bll-contracting-password)"
          RabbitMQPod: ''
          RabbitMQUsername: "$(RABBITMQ_USERNAME)"
          RabbitMQVirtualHost: ''
      - taskId: 76a92167-7c70-4b54-ba35-13d5819c9b1e
        version: 2.*
        name: 'Task group: K8S Deploy V3 bll-contracting'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          HelmArtifact: ''
          KubernetesDeploymentName: bll-contracting
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          KubernetesObjectType: ''
          SecretValues: ESB_KEYSTORE_PW=$(esb-hhn544-password),ESB_KEYSTORE_FILE=$(esb-hhn544-value),BLL_JWKS_ENCRYPTION=$(bll-jwks-encryption),BLL_JWKS_SIGNATURE=$(bll-jwks-signature),RABBITMQ_PASSWORD=$(rabbitmq-bll-contracting-password)
    preDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: false
        isNotificationOn: false
        approver:
          id: c48d7901-feca-403b-b698-cf99c6e7d602
          isContainer: true
      approvalOptions:
        releaseCreatorCanBeApprover: true
    postDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
  - name: ACC-NE
    rank: 4
    environmentOptions:
      emailNotificationType: Always
      publishDeploymentStatus: true
    executionPolicy:
      concurrencyCount: 1
    retentionPolicy:
      daysToKeep: 30
      releasesToKeep: 10
      retainBuild: true
    variables: {}
    variableGroups:
    - 113
    - 23
    deployPhases:
    - name: Agent phase
      rank: 1
      phaseType: 1
      deploymentInput:
        queueId: 164
      workflowTasks:
      - taskId: 1e244d32-2dd4-4165-96fb-b7441ca9331e
        version: 1.*
        name: 'Azure Key Vault: webfoundation-acc-akv'
        enabled: true
        definitionType: task
        inputs:
          ConnectedServiceName: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KeyVaultName: webfoundation-acc-akv
          SecretsFilter: "*"
      - taskId: 93a67d85-4982-4e19-87dd-29311c974748
        version: 2.*
        name: 'Task group: Create RabbitMQ user'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          RabbitMQPassword: "$(rabbitmq-bll-contracting-password)"
          RabbitMQPod: ''
          RabbitMQUsername: "$(RABBITMQ_USERNAME)"
          RabbitMQVirtualHost: ''
      - taskId: 76a92167-7c70-4b54-ba35-13d5819c9b1e
        version: 2.*
        name: 'Task group: K8S Deploy V3 bll-contracting'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          HelmArtifact: ''
          KubernetesDeploymentName: bll-contracting
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          KubernetesObjectType: ''
          SecretValues: ESB_KEYSTORE_PW=$(esb-hhn544-password),ESB_KEYSTORE_FILE=$(esb-hhn544-value),BLL_JWKS_ENCRYPTION=$(bll-jwks-encryption),BLL_JWKS_SIGNATURE=$(bll-jwks-signature),RABBITMQ_PASSWORD=$(rabbitmq-bll-contracting-password)
    preDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: false
        isNotificationOn: false
        approver:
          id: c48d7901-feca-403b-b698-cf99c6e7d602
          isContainer: true
      approvalOptions:
        releaseCreatorCanBeApprover: true
    postDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
  - name: PRD-WE
    rank: 5
    environmentOptions:
      emailNotificationType: Always
      publishDeploymentStatus: true
    executionPolicy:
      concurrencyCount: 1
    retentionPolicy:
      daysToKeep: 30
      releasesToKeep: 10
      retainBuild: true
    variables: {}
    variableGroups:
    - 113
    - 25
    deployPhases:
    - name: Agent phase
      rank: 1
      phaseType: 1
      deploymentInput:
        queueId: 165
      workflowTasks:
      - taskId: 1e244d32-2dd4-4165-96fb-b7441ca9331e
        version: 1.*
        name: 'Azure Key Vault: webfoundation-prd-akv'
        enabled: true
        definitionType: task
        inputs:
          ConnectedServiceName: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KeyVaultName: webfoundation-prd-akv
          SecretsFilter: "*"
      - taskId: 93a67d85-4982-4e19-87dd-29311c974748
        version: 2.*
        name: 'Task group: Create RabbitMQ user'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          RabbitMQPassword: "$(rabbitmq-bll-contracting-password)"
          RabbitMQPod: ''
          RabbitMQUsername: "$(RABBITMQ_USERNAME)"
          RabbitMQVirtualHost: ''
      - taskId: 76a92167-7c70-4b54-ba35-13d5819c9b1e
        version: 2.*
        name: 'Task group: K8S Deploy V3 bll-contracting'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          HelmArtifact: ''
          KubernetesDeploymentName: bll-contracting
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          KubernetesObjectType: ''
          SecretValues: ESB_KEYSTORE_PW=$(esb-gim597-password),ESB_KEYSTORE_FILE=$(esb-gim597-value),BLL_JWKS_ENCRYPTION=$(bll-jwks-encryption),BLL_JWKS_SIGNATURE=$(bll-jwks-signature),RABBITMQ_PASSWORD=$(rabbitmq-bll-contracting-password)
    preDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: false
        isNotificationOn: false
        approver:
          id: e9a38fdf-a890-4227-909e-c438dc074464
          isContainer: true
      approvalOptions:
        releaseCreatorCanBeApprover: true
    postDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
  - name: PRD-NE
    rank: 6
    environmentOptions:
      emailNotificationType: Always
      publishDeploymentStatus: true
    executionPolicy:
      concurrencyCount: 1
    retentionPolicy:
      daysToKeep: 30
      releasesToKeep: 10
      retainBuild: true
    variables: {}
    variableGroups:
    - 113
    - 23
    deployPhases:
    - name: Agent phase
      rank: 1
      phaseType: 1
      deploymentInput:
        queueId: 164
      workflowTasks:
      - taskId: 1e244d32-2dd4-4165-96fb-b7441ca9331e
        version: 1.*
        name: 'Azure Key Vault: webfoundation-prd-akv'
        enabled: true
        definitionType: task
        inputs:
          ConnectedServiceName: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KeyVaultName: webfoundation-prd-akv
          SecretsFilter: "*"
      - taskId: 93a67d85-4982-4e19-87dd-29311c974748
        version: 2.*
        name: 'Task group: Create RabbitMQ user'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          RabbitMQPassword: "$(rabbitmq-bll-contracting-password)"
          RabbitMQPod: ''
          RabbitMQUsername: "$(RABBITMQ_USERNAME)"
          RabbitMQVirtualHost: ''
      - taskId: 76a92167-7c70-4b54-ba35-13d5819c9b1e
        version: 2.*
        name: 'Task group: K8S Deploy V3 bll-contracting'
        enabled: true
        definitionType: metaTask
        inputs:
          AksCluster: "$(AKS_CLUSTER)"
          AzureResourceGroup: "$(AZURE_RESOURCE_GROUP)"
          AzureSubscription: 6714e6c3-6518-4050-90ec-ed7288c13b3a
          HelmArtifact: ''
          KubernetesDeploymentName: bll-contracting
          KubernetesNamespace: "$(K8S_NAMESPACE)"
          KubernetesObjectType: ''
          SecretValues: ESB_KEYSTORE_PW=$(esb-gim597-password),ESB_KEYSTORE_FILE=$(esb-gim597-value),BLL_JWKS_ENCRYPTION=$(bll-jwks-encryption),BLL_JWKS_SIGNATURE=$(bll-jwks-signature),RABBITMQ_PASSWORD=$(rabbitmq-bll-contracting-password)
    preDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: false
        isNotificationOn: false
        approver:
          id: e9a38fdf-a890-4227-909e-c438dc074464
          isContainer: true
      approvalOptions:
        releaseCreatorCanBeApprover: true
    postDeployApprovals:
      approvals:
      - rank: 1
        isAutomated: true
        isNotificationOn: false
      approvalOptions:
        releaseCreatorCanBeApprover: false
  artifacts:
  - type: Build
    alias: BLL-Contracting CI
    definitionReference:
      defaultVersionType:
        id: latestType
        name: Latest
      definition:
        id: '228'
      project:
        id: 5a4ec25a-2f9d-4947-9937-d4347eaceadd
