---
apiVersion: v1
kind: Config
servers:
  - server:
      type: azure-devops
      base-url: https://dev.azure.com/${organization}
    name: server-azure-devops
contexts:
  - context:
      server: server-azure-devops
      namespace: ${project}
      user: user-azure-devops
      plugins:
        - '@kroonprins/pipectl-azure-devops'
    name: context-azure-devops
current-context: context-azure-devops
users:
  - user:
      auth-provider:
        config:
          token: ${personal access token}
        name: azure-devops-personal-access-token
    name: user-azure-devops
